# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import asistencias_pb2 as asistencias__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in asistencias_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AsistenciasServiceStub(object):
    """=============================================
    MS-5: Asistencias QR — EXPOSICIÓN gRPC
    Puerto: 50055
    =============================================
    Consumido por MS-7 para generar reportes de asistencia.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAsistenciaAlumno = channel.unary_unary(
                '/agm.asistencias.AsistenciasService/GetAsistenciaAlumno',
                request_serializer=asistencias__pb2.GetAsistenciaAlumnoRequest.SerializeToString,
                response_deserializer=asistencias__pb2.AsistenciaAlumnoResponse.FromString,
                _registered_method=True)
        self.GetEstadisticasAsistencia = channel.unary_unary(
                '/agm.asistencias.AsistenciasService/GetEstadisticasAsistencia',
                request_serializer=asistencias__pb2.GetEstadisticasAsistenciaRequest.SerializeToString,
                response_deserializer=asistencias__pb2.EstadisticasAsistenciaResponse.FromString,
                _registered_method=True)


class AsistenciasServiceServicer(object):
    """=============================================
    MS-5: Asistencias QR — EXPOSICIÓN gRPC
    Puerto: 50055
    =============================================
    Consumido por MS-7 para generar reportes de asistencia.

    """

    def GetAsistenciaAlumno(self, request, context):
        """Obtiene el historial de asistencias de un alumno en una materia
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEstadisticasAsistencia(self, request, context):
        """Obtiene estadísticas generales de asistencia de una materia
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AsistenciasServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAsistenciaAlumno': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAsistenciaAlumno,
                    request_deserializer=asistencias__pb2.GetAsistenciaAlumnoRequest.FromString,
                    response_serializer=asistencias__pb2.AsistenciaAlumnoResponse.SerializeToString,
            ),
            'GetEstadisticasAsistencia': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEstadisticasAsistencia,
                    request_deserializer=asistencias__pb2.GetEstadisticasAsistenciaRequest.FromString,
                    response_serializer=asistencias__pb2.EstadisticasAsistenciaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agm.asistencias.AsistenciasService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agm.asistencias.AsistenciasService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AsistenciasService(object):
    """=============================================
    MS-5: Asistencias QR — EXPOSICIÓN gRPC
    Puerto: 50055
    =============================================
    Consumido por MS-7 para generar reportes de asistencia.

    """

    @staticmethod
    def GetAsistenciaAlumno(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agm.asistencias.AsistenciasService/GetAsistenciaAlumno',
            asistencias__pb2.GetAsistenciaAlumnoRequest.SerializeToString,
            asistencias__pb2.AsistenciaAlumnoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEstadisticasAsistencia(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agm.asistencias.AsistenciasService/GetEstadisticasAsistencia',
            asistencias__pb2.GetEstadisticasAsistenciaRequest.SerializeToString,
            asistencias__pb2.EstadisticasAsistenciaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
