# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reportes.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'reportes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ereportes.proto\x12\x08reportes\"J\n\x15GenerateReportRequest\x12\x0c\n\x04tipo\x18\x01 \x01(\t\x12\x12\n\nmateria_id\x18\x02 \x01(\x05\x12\x0f\n\x07\x66ormato\x18\x03 \x01(\t\"Z\n\x0eReportResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07\x61rchivo\x18\x02 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x04 \x01(\t\"0\n\x1aGetHistorialDocenteRequest\x12\x12\n\ndocente_id\x18\x01 \x01(\x05\"\xdc\x01\n\x0cStatsPeriodo\x12\x16\n\x0eperiodo_nombre\x18\x01 \x01(\t\x12\x12\n\nperiodo_id\x18\x02 \x01(\x05\x12\x16\n\x0emateria_nombre\x18\x03 \x01(\t\x12\x12\n\nmateria_id\x18\x04 \x01(\x05\x12\x15\n\rtotal_alumnos\x18\x05 \x01(\x05\x12\x11\n\taprobados\x18\x06 \x01(\x05\x12\x12\n\nreprobados\x18\x07 \x01(\x05\x12\x17\n\x0fpromedio_grupal\x18\x08 \x01(\x01\x12\x1d\n\x15porcentaje_asistencia\x18\t \x01(\x01\"X\n\x18HistorialDocenteResponse\x12\x12\n\ndocente_id\x18\x01 \x01(\x05\x12(\n\x08periodos\x18\x02 \x03(\x0b\x32\x16.reportes.StatsPeriodo2\xbf\x01\n\x0fReportesService\x12K\n\x0eGenerateReport\x12\x1f.reportes.GenerateReportRequest\x1a\x18.reportes.ReportResponse\x12_\n\x13GetHistorialDocente\x12$.reportes.GetHistorialDocenteRequest\x1a\".reportes.HistorialDocenteResponseB\x14\n\x10\x63om.agm.reportesP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reportes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.agm.reportesP\001'
  _globals['_GENERATEREPORTREQUEST']._serialized_start=28
  _globals['_GENERATEREPORTREQUEST']._serialized_end=102
  _globals['_REPORTRESPONSE']._serialized_start=104
  _globals['_REPORTRESPONSE']._serialized_end=194
  _globals['_GETHISTORIALDOCENTEREQUEST']._serialized_start=196
  _globals['_GETHISTORIALDOCENTEREQUEST']._serialized_end=244
  _globals['_STATSPERIODO']._serialized_start=247
  _globals['_STATSPERIODO']._serialized_end=467
  _globals['_HISTORIALDOCENTERESPONSE']._serialized_start=469
  _globals['_HISTORIALDOCENTERESPONSE']._serialized_end=557
  _globals['_REPORTESSERVICE']._serialized_start=560
  _globals['_REPORTESSERVICE']._serialized_end=751
# @@protoc_insertion_point(module_scope)
