# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agm_common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'agm_common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61gm_common.proto\x12\nagm.common\"\x07\n\x05\x45mpty\"I\n\nUserClaims\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0e\n\x06nombre\x18\x03 \x01(\t\x12\x0b\n\x03rol\x18\x04 \x01(\t\"-\n\x15\x41\x63\x63\x65ssTokenCredential\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\"r\n\x15TokenValidationResult\x12\r\n\x05valid\x18\x01 \x01(\x08\x12$\n\x04user\x18\x02 \x01(\x0b\x32\x16.agm.common.UserClaims\x12\x0b\n\x03jti\x18\x03 \x01(\t\x12\x17\n\x0f\x65xpires_at_unix\x18\x04 \x01(\x03\"J\n\x16TokenRevocationPayload\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0b\n\x03jti\x18\x02 \x01(\t\x12\x12\n\ntoken_type\x18\x03 \x01(\t\"I\n\x15PasswordResetDelivery\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x11\n\treset_url\x18\x02 \x01(\t\x12\x0e\n\x06nombre\x18\x03 \x01(\t\"A\n\x19SigningKeysRotatedPayload\x12\x0b\n\x03kid\x18\x01 \x01(\t\x12\x17\n\x0frotated_at_unix\x18\x02 \x01(\x03\x42\x12\n\x0e\x63om.agm.commonP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agm_common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016com.agm.commonP\001'
  _globals['_EMPTY']._serialized_start=32
  _globals['_EMPTY']._serialized_end=39
  _globals['_USERCLAIMS']._serialized_start=41
  _globals['_USERCLAIMS']._serialized_end=114
  _globals['_ACCESSTOKENCREDENTIAL']._serialized_start=116
  _globals['_ACCESSTOKENCREDENTIAL']._serialized_end=161
  _globals['_TOKENVALIDATIONRESULT']._serialized_start=163
  _globals['_TOKENVALIDATIONRESULT']._serialized_end=277
  _globals['_TOKENREVOCATIONPAYLOAD']._serialized_start=279
  _globals['_TOKENREVOCATIONPAYLOAD']._serialized_end=353
  _globals['_PASSWORDRESETDELIVERY']._serialized_start=355
  _globals['_PASSWORDRESETDELIVERY']._serialized_end=428
  _globals['_SIGNINGKEYSROTATEDPAYLOAD']._serialized_start=430
  _globals['_SIGNINGKEYSROTATEDPAYLOAD']._serialized_end=495
# @@protoc_insertion_point(module_scope)
