# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notificaciones.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'notificaciones.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14notificaciones.proto\x12\x0enotificaciones\"0\n\x0cSendResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"T\n\x15SendBienvenidaRequest\x12\x11\n\talumno_id\x18\x01 \x01(\x05\x12\x12\n\nmateria_id\x18\x02 \x01(\x05\x12\x14\n\x0c\x63lave_acceso\x18\x03 \x01(\t\"L\n\x0fSendBajaRequest\x12\x11\n\talumno_id\x18\x01 \x01(\x05\x12\x12\n\ndocente_id\x18\x02 \x01(\x05\x12\x12\n\nmateria_id\x18\x03 \x01(\x05\".\n\x18SendCierreMateriaRequest\x12\x12\n\nmateria_id\x18\x01 \x01(\x05\"K\n\x18SendResetPasswordRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\x12\x11\n\treset_url\x18\x03 \x01(\t2\xf8\x02\n\x15NotificacionesService\x12U\n\x0eSendBienvenida\x12%.notificaciones.SendBienvenidaRequest\x1a\x1c.notificaciones.SendResponse\x12N\n\rSendBajaNotif\x12\x1f.notificaciones.SendBajaRequest\x1a\x1c.notificaciones.SendResponse\x12[\n\x11SendCierreMateria\x12(.notificaciones.SendCierreMateriaRequest\x1a\x1c.notificaciones.SendResponse\x12[\n\x11SendResetPassword\x12(.notificaciones.SendResetPasswordRequest\x1a\x1c.notificaciones.SendResponseB\x1a\n\x16\x63om.agm.notificacionesP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notificaciones_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.agm.notificacionesP\001'
  _globals['_SENDRESPONSE']._serialized_start=40
  _globals['_SENDRESPONSE']._serialized_end=88
  _globals['_SENDBIENVENIDAREQUEST']._serialized_start=90
  _globals['_SENDBIENVENIDAREQUEST']._serialized_end=174
  _globals['_SENDBAJAREQUEST']._serialized_start=176
  _globals['_SENDBAJAREQUEST']._serialized_end=252
  _globals['_SENDCIERREMATERIAREQUEST']._serialized_start=254
  _globals['_SENDCIERREMATERIAREQUEST']._serialized_end=300
  _globals['_SENDRESETPASSWORDREQUEST']._serialized_start=302
  _globals['_SENDRESETPASSWORDREQUEST']._serialized_end=377
  _globals['_NOTIFICACIONESSERVICE']._serialized_start=380
  _globals['_NOTIFICACIONESSERVICE']._serialized_end=756
# @@protoc_insertion_point(module_scope)
