# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notificaciones.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'notificaciones.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import agm_common_pb2 as agm__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14notificaciones.proto\x12\x12\x61gm.notificaciones\x1a\x10\x61gm_common.proto\"0\n\x0cSendResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"T\n\x15SendBienvenidaRequest\x12\x11\n\talumno_id\x18\x01 \x01(\x05\x12\x12\n\nmateria_id\x18\x02 \x01(\x05\x12\x14\n\x0c\x63lave_acceso\x18\x03 \x01(\t\"L\n\x0fSendBajaRequest\x12\x11\n\talumno_id\x18\x01 \x01(\x05\x12\x12\n\ndocente_id\x18\x02 \x01(\x05\x12\x12\n\nmateria_id\x18\x03 \x01(\x05\".\n\x18SendCierreMateriaRequest\x12\x12\n\nmateria_id\x18\x01 \x01(\x05\"O\n\x18SendResetPasswordRequest\x12\x33\n\x08\x64\x65livery\x18\x01 \x01(\x0b\x32!.agm.common.PasswordResetDelivery2\x98\x03\n\x15NotificacionesService\x12]\n\x0eSendBienvenida\x12).agm.notificaciones.SendBienvenidaRequest\x1a .agm.notificaciones.SendResponse\x12V\n\rSendBajaNotif\x12#.agm.notificaciones.SendBajaRequest\x1a .agm.notificaciones.SendResponse\x12\x63\n\x11SendCierreMateria\x12,.agm.notificaciones.SendCierreMateriaRequest\x1a .agm.notificaciones.SendResponse\x12\x63\n\x11SendResetPassword\x12,.agm.notificaciones.SendResetPasswordRequest\x1a .agm.notificaciones.SendResponseB\x1a\n\x16\x63om.agm.notificacionesP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notificaciones_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.agm.notificacionesP\001'
  _globals['_SENDRESPONSE']._serialized_start=62
  _globals['_SENDRESPONSE']._serialized_end=110
  _globals['_SENDBIENVENIDAREQUEST']._serialized_start=112
  _globals['_SENDBIENVENIDAREQUEST']._serialized_end=196
  _globals['_SENDBAJAREQUEST']._serialized_start=198
  _globals['_SENDBAJAREQUEST']._serialized_end=274
  _globals['_SENDCIERREMATERIAREQUEST']._serialized_start=276
  _globals['_SENDCIERREMATERIAREQUEST']._serialized_end=322
  _globals['_SENDRESETPASSWORDREQUEST']._serialized_start=324
  _globals['_SENDRESETPASSWORDREQUEST']._serialized_end=403
  _globals['_NOTIFICACIONESSERVICE']._serialized_start=406
  _globals['_NOTIFICACIONESSERVICE']._serialized_end=814
# @@protoc_insertion_point(module_scope)
