# Generated by Django 6.0.5 on 2026-05-16 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('plan_estudios', models.CharField(blank=True, default='', max_length=100)),
                ('activo', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'periodos',
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('activo',), name='unique_periodo_activo')],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrc', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('seccion', models.CharField(max_length=10)),
                ('clave', models.CharField(max_length=20)),
                ('docente_nombre', models.CharField(blank=True, default='', max_length=255)),
                ('docente_id', models.IntegerField(blank=True, null=True)),
                ('horario', models.CharField(blank=True, default='', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='core.periodo')),
            ],
            options={
                'db_table': 'materias',
                'unique_together': {('periodo', 'nrc')},
            },
        ),
    ]
