# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: periodos.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'periodos.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eperiodos.proto\x12\x0c\x61gm.periodos\"+\n\x15GetMateriaByIdRequest\x12\x12\n\nmateria_id\x18\x01 \x01(\x05\"\xbf\x01\n\x0bMateriaInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03nrc\x18\x02 \x01(\t\x12\x0e\n\x06nombre\x18\x03 \x01(\t\x12\x0f\n\x07seccion\x18\x04 \x01(\t\x12\r\n\x05\x63lave\x18\x05 \x01(\t\x12\x16\n\x0e\x64ocente_nombre\x18\x06 \x01(\t\x12\x12\n\ndocente_id\x18\x07 \x01(\x05\x12\x0f\n\x07horario\x18\x08 \x01(\t\x12\x12\n\nperiodo_id\x18\t \x01(\x05\x12\x16\n\x0eperiodo_nombre\x18\n \x01(\t\"1\n\x1bGetMateriasByDocenteRequest\x12\x12\n\ndocente_id\x18\x01 \x01(\x05\"C\n\x14MateriasListResponse\x12+\n\x08materias\x18\x01 \x03(\x0b\x32\x19.agm.periodos.MateriaInfo\"\x19\n\x17GetPeriodoActivoRequest\"y\n\x0bPeriodoInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x14\n\x0c\x66\x65\x63ha_inicio\x18\x03 \x01(\t\x12\x11\n\tfecha_fin\x18\x04 \x01(\t\x12\x15\n\rplan_estudios\x18\x05 \x01(\t\x12\x0e\n\x06\x61\x63tivo\x18\x06 \x01(\x08\x32\xa0\x02\n\x0fPeriodosService\x12P\n\x0eGetMateriaById\x12#.agm.periodos.GetMateriaByIdRequest\x1a\x19.agm.periodos.MateriaInfo\x12\x65\n\x14GetMateriasByDocente\x12).agm.periodos.GetMateriasByDocenteRequest\x1a\".agm.periodos.MateriasListResponse\x12T\n\x10GetPeriodoActivo\x12%.agm.periodos.GetPeriodoActivoRequest\x1a\x19.agm.periodos.PeriodoInfoB\x14\n\x10\x63om.agm.periodosP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'periodos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.agm.periodosP\001'
  _globals['_GETMATERIABYIDREQUEST']._serialized_start=32
  _globals['_GETMATERIABYIDREQUEST']._serialized_end=75
  _globals['_MATERIAINFO']._serialized_start=78
  _globals['_MATERIAINFO']._serialized_end=269
  _globals['_GETMATERIASBYDOCENTEREQUEST']._serialized_start=271
  _globals['_GETMATERIASBYDOCENTEREQUEST']._serialized_end=320
  _globals['_MATERIASLISTRESPONSE']._serialized_start=322
  _globals['_MATERIASLISTRESPONSE']._serialized_end=389
  _globals['_GETPERIODOACTIVOREQUEST']._serialized_start=391
  _globals['_GETPERIODOACTIVOREQUEST']._serialized_end=416
  _globals['_PERIODOINFO']._serialized_start=418
  _globals['_PERIODOINFO']._serialized_end=539
  _globals['_PERIODOSSERVICE']._serialized_start=542
  _globals['_PERIODOSSERVICE']._serialized_end=830
# @@protoc_insertion_point(module_scope)
