# Generated by Django 6.0.5 on 2026-05-19 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SesionAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia_id', models.IntegerField(db_index=True, help_text='ID de la materia (desde MS-3)')),
                ('docente_id', models.IntegerField(help_text='ID del docente titular que inicia la sesión')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, help_text='Timestamp de inicio de la sesión (en UTC)')),
                ('fecha_fin_teorica', models.DateTimeField(help_text='Fecha teórica de fin = inicio + 10 minutos')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cerrada', 'Cerrada'), ('confirmada', 'Confirmada')], default='activa', help_text='Estado de la sesión: activa, cerrada, confirmada', max_length=20)),
                ('activa', models.BooleanField(db_index=True, default=True, help_text='Flag para Query rápida de sesiones activas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sesión de Asistencia',
                'verbose_name_plural': 'Sesiones de Asistencia',
                'db_table': 'sesion_asistencia',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['materia_id', 'activa'], name='sesion_asis_materia_a1e246_idx'), models.Index(fields=['docente_id', 'activa'], name='sesion_asis_docente_09d0a4_idx'), models.Index(fields=['fecha_inicio'], name='sesion_asis_fecha_i_5caa95_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno_id', models.IntegerField(db_index=True, help_text='ID del alumno (desde MS-3)')),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('retardo', 'Retardo'), ('ausente', 'Ausente')], default='ausente', help_text='Clasificación: presente, retardo, ausente', max_length=20)),
                ('minuto_registro', models.IntegerField(help_text='Minuto dentro de la sesión (0-10) en que se registró')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Timestamp exacto del registro')),
                ('qr_payload_hash', models.CharField(blank=True, help_text='Hash SHA256 del payload QR para traceabilidad', max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sesion', models.ForeignKey(help_text='Referencia a la sesión de asistencia', on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='core.sesionasistencia')),
            ],
            options={
                'verbose_name': 'Registro de Asistencia',
                'verbose_name_plural': 'Registros de Asistencia',
                'db_table': 'registro_asistencia',
                'ordering': ['fecha_registro'],
                'indexes': [models.Index(fields=['sesion', 'alumno_id'], name='registro_as_sesion__a5faea_idx'), models.Index(fields=['alumno_id', 'estado'], name='registro_as_alumno__f0c983_idx'), models.Index(fields=['sesion', 'estado'], name='registro_as_sesion__aa8956_idx'), models.Index(fields=['fecha_registro'], name='registro_as_fecha_r_ea1b0b_idx')],
                'unique_together': {('sesion', 'alumno_id')},
            },
        ),
    ]
