# Generated by Django 6.0.5 on 2026-05-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fix_mysql_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionmateria',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
